name: 'duckdb_project'
version: '1.0.0'

profile: 'duckdb'

config-version: 2

model-paths: ["models"]

models:
  duckdb_project:
    raw:
      +schema: raw
    transformed:
      +schema: transformed
