name: "duckdb_project"
version: "1.0"
profile: "duckdb_profile"
config-version: 2

# Define paths
model-paths: ["models"]
test-paths: ["tests"]

# Target the raw and transformed data
data-paths: []
target-path: "target"
