version: "3.8"

services:
  mongodb_fetcher:
    build:
      context: ./mongodb
    volumes:
      - ./data/raw:/data
    env_file:
      - ./mongodb/.env
    networks:
      - duckdb_network
    command: ["python", "fetch_data.py"]
    healthcheck:
      test: ["CMD", "test", "-f", "/data/mongodb_fetch_complete.flag"]
      interval: 10s
      retries: 5
      start_period: 20s
      timeout: 5s

  duckdb_raw_loader:
    build:
      context: ./duckdb_1
    volumes:
      - ./data/raw:/data
      - ./duckdb_1/database:/duckdb_1/database
    depends_on:
      mongodb_fetcher:
        condition: service_completed_successfully
    networks:
      - duckdb_network
    command: ["python", "load_to_duckdb.py"]
    healthcheck:
      test: ["CMD", "test", "-f", "/duckdb_1/database/raw_data_complete.flag"]
      interval: 10s
      retries: 5
      start_period: 20s
      timeout: 5s

  dbt_transformer:
    build:
      context: ./dbt
    volumes:
      - ./data/transformed:/data/transformed
      - ./duckdb_1/database:/duckdb_1/database
      - ~/.dbt/profiles.yml:/root/.dbt/profiles.yml
    depends_on:
      duckdb_raw_loader:
        condition: service_completed_successfully
    networks:
      - duckdb_network
    command: ["python", "wait_for_transformations_and_tests.py"]
    healthcheck:
      test: ["CMD", "test", "-f", "/duckdb_1/database/dbt_complete.flag"]
      interval: 10s
      retries: 5
      start_period: 20s
      timeout: 5s
    environment:
      - DBT_LOG_LEVEL=DEBUG

  duckdb_transformed_loader:
    build:
      context: ./duckdb_1
    volumes:
      - ./data/transformed:/data/transformed
      - ./duckdb_1/database:/duckdb_1/database
    depends_on:
      dbt_transformer:
        condition: service_completed_successfully
    networks:
      - duckdb_network
    command: ["python", "load_transformed_to_duckdb.py"]
    healthcheck:
      test: ["CMD", "test", "-f", "/duckdb_1/database/transformed_data_complete.flag"]
      interval: 10s
      retries: 5
      start_period: 20s
      timeout: 5s

networks:
  duckdb_network:
    driver: bridge
