version: "3.8"

services:
  mongodb_fetcher:
    build:
      context: ./mongodb
    volumes:
      - ./data/raw:/data  # Maps raw data directory for JSON files
    env_file:
      - ./mongodb/.env  # Load environment variables for MongoDB connection
    networks:
      - duckdb_network
    command: ["python", "fetch_data.py"]
    restart: "no"
    healthcheck:
      test: ["CMD", "test", "-f", "/data/mongodb_fetch_complete.flag"]
      interval: 10s
      retries: 5
      start_period: 20s
      timeout: 5s

  duckdb_raw_loader:
    build:
      context: ./duckdb_1
    volumes:
      - ./data/raw:/data  # Raw JSON files
      - ./duckdb_1/database:/duckdb_1/database  # Maps DuckDB directory
    depends_on:
      mongodb_fetcher:
        condition: service_completed_successfully
    networks:
      - duckdb_network
    command: ["python", "load_to_duckdb.py"]

  dbt_transformer:
    build:
      context: ./dbt
    volumes:
      - ./duckdb_1/database:/duckdb_1/database  # Maps DuckDB directory
      - ~/.dbt/profiles.yml:/root/.dbt/profiles.yml  # Mount the profiles.yml for DBT
      - ./dbt/models:/dbt/models  # Models directory
      - ./dbt/wait_for_transformations_and_tests.py:/dbt/wait_for_transformations_and_tests.py
    depends_on:
      - duckdb_raw_loader
    networks:
      - duckdb_network
    command: ["python", "wait_for_transformations_and_tests.py"]

  duckdb_transformed_loader:
    build:
      context: ./duckdb_1
    volumes:
      - ./duckdb_1/database:/duckdb_1/database  # Maps DuckDB directory
    depends_on:
      dbt_transformer:
        condition: service_completed_successfully
    networks:
      - duckdb_network
    command: ["python", "load_transformed_to_duckdb.py"]

networks:
  duckdb_network:
    driver: bridge
