version: "3.8"

services:
  mongodb_fetcher:
    build:
      context: ./mongodb
    volumes:
      - ./data/raw:/data  # Maps raw data directory for JSON files
    env_file:
      - ./mongodb/.env  # Load environment variables
    networks:
      - duckdb_network
    command: ["python", "fetch_data.py"]
    restart: "no"
    healthcheck:
      test: ["CMD", "test", "-f", "/data/mongodb_fetch_complete.flag"]
      interval: 10s
      retries: 5
      start_period: 20s
      timeout: 5s

  duckdb_raw_loader:
    build:
      context: ./duckdb_1
    volumes:
      - ./data/raw:/data  # Maps raw data directory
      - ./duckdb_1/database:/duckdb_1  # Maps DuckDB directory
    depends_on:
      mongodb_fetcher:
        condition: service_completed_successfully
    networks:
      - duckdb_network
    command: ["python", "load_to_duckdb.py"]

networks:
  duckdb_network:
    driver: bridge
