version: 2

models:
  - name: users
    description: "Raw users data fetched from MongoDB."
    columns:
      - name: _id
        description: "Unique identifier for the user."
        tests:
          - unique
          - not_null
      - name: email
        description: "Email address of the user."
        tests:
          - not_null
      - name: name
        description: "Name of the user."
        tests:
          - not_null

  - name: comments
    description: "Raw comments data fetched from MongoDB."
    columns:
      - name: _id
        description: "Unique identifier for the comment."
        tests:
          - unique
          - not_null
      - name: movie_id
        description: "Reference to the movie for which the comment was made."
        tests:
          - not_null
      - name: name
        description: "Name of the user who made the comment."
        tests:
          - not_null

  - name: movies
    description: "Raw movies data fetched from MongoDB."
    columns:
      - name: _id
        description: "Unique identifier for the movie."
        tests:
          - unique
          - not_null
      - name: genres
        description: "Genres associated with the movie."
        tests:
          - not_null
      - name: metacritic
        description: "Metacritic score of the movie."
        tests:
          - not_null
